class Images{
  static const splashLogo = 'assets/logos/diamond_splash_logo.svg';
  static const appBarScanner = 'assets/icons/scanner_icon.svg';
  static const introductionLogo_1 = 'assets/images/introduction_image_1.png';
  static const introductionLogo_2 = 'assets/images/introduction_image_2.png';
  static const introductionLogo_3 = 'assets/images/introduction_image_3.png';
  static const creditCardPayPassIcon = 'assets/icons/credit_card_pay_pass_icon.svg';
  static const creditCardSimLogo = 'assets/logos/credit_card_sim_logo.svg';
  static const masterCardLogo = 'assets/logos/master_card_logo.svg';
  static const rectangle_2_1 = 'assets/logos/rectangle_2.1.svg';
  static const rectangle_2_2 = 'assets/logos/rectangle_2.2.svg';
  static const rectangle_2_3 = 'assets/logos/rectangle_2.3.svg';
  static const rectangle_2_4 = 'assets/logos/rectangle_2.4.svg';
  static const btcLogo = 'assets/images/btc_logo.png';
  static const btcChart = 'assets/images/btc_chart.png';
  static const ethLogo ='assets/images/eth_logo.png';
  static const ethChart ='assets/images/eth_chart.png';
  static const ltcLogo ='assets/images/ltc_logo.png';
  static const ltcChart ='assets/images/ltc_chart.png';
  static const xrpLogo ='assets/images/xrp_logo.png';
  static const xrpChart ='assets/images/xrp_chart.png';
  static const historyIcon ='assets/icons/history_icon.png';
  static const settingIcon ='assets/icons/setting_icon.png';
  static const withDrawIcon ='assets/icons/withdraw_icon.png';
  static const transferIcon ='assets/icons/transfer_icon.png';
  static const statisticIcon ='assets/icons/statistic_icon.png';
  static const portfolioIcon ='assets/icons/portfolio_icon.png';
  static const walletIcon ='assets/icons/wallet_icon.png';
}